language: node_js
sudo: true
node_js:
  - '0.12'

branches:
  only:
    - master
    
script: echo 0

after_success:
  - sudo $(which npm) install -g firebase-tools
  - if [[ "${TRAVIS_PULL_REQUEST}" == "false" ]]; then firebase deploy --email $FIREBASE_EMAIL --password $FIREBASE_PASSWORD; fi
