language: node_js
sudo: false
node_js:
  - '0.12'

branches:
  only:
    - master

script:
  - echo 0

after_success:
  - $(which npm) install -g firebase-tools
  - if [[ "${TRAVIS_PULL_REQUEST}" == "false" ]]; then firebase deploy --email $FIREBASE_EMAIL --password $FIREBASE_PASSWORD; fi
