language: node_js
sudo: false
node_js:
  - 4.2.3

branches:
  only:
    - master

script:
  - echo 0

after_success:
  - $(which npm) install -g firebase-tools
  - if [[ "${TRAVIS_PULL_REQUEST}" == "false" ]]; then firebase deploy --token $FIREBASE_TOKEN; fi
